### ISSUE TITLE
bundler: failed to load command: src/main.rb (src/main.rb)

### ISSUE THREAD

**Issue by Twooearly** [solectrus/senec-importer#3]
Hallo,

Ich bin es (leider) nochmal. Ich habe nun alles zum laufen gebracht und alles funktioniert auch perfekt.
Nur leider bekomme ich den Import der alten Daten nicht hin. Ich habe mir schon den alten Fehler Report von spirit0607 angeschaut und die Schritte befolgt, nur bekomme ich nun folgende Fehlermeldung: `bundler: failed to load command: src/main.rb (src/main.rb)`
Woran könnte das liegen?
Hier einmal der komplette Log:

```
root@homeserver:/var/lib/docker/history# docker run -it --rm            --env-file .env            --env INFLUX_HOST=192.168.200.222            -v /var/lib/docker/history/data:/data            ghcr.io/solectrus/senec-importer
SENEC CSV importer for SOLECTRUS
https://github.com/solectrus/senec-importer
Copyright (c) 2020,2022 Georg Ledermann, released under the MIT License

Using Ruby 3.1.2 on platform x86_64-linux-musl
Pushing to InfluxDB at http://192.168.200.222:8086, bucket my-solectrus-bucket

Importing data from /data ...
Importing /data/S21627181110462487540422709-week-10-2022.csv... bundler: failed to load command: src/main.rb (src/main.rb)
/usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/default_api.rb:109:in `rescue in _request': Connection reset by peer (InfluxDB2::InfluxError)
        from /usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/default_api.rb:108:in `_request'
        from /usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/default_api.rb:59:in `_post_text'
        from /usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/write_api.rb:214:in `write_raw'
        from /usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/write_api.rb:186:in `write'
        from /senec-importer/src/flux_writer.rb:17:in `push'
        from /senec-importer/src/flux_writer.rb:11:in `push'
        from /senec-importer/src/import.rb:36:in `process'
        from /senec-importer/src/import.rb:11:in `block in run'
        from /senec-importer/src/import.rb:10:in `each'
        from /senec-importer/src/import.rb:10:in `run'
        from src/main.rb:20:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:486:in `exec'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:25:in `start'
        from /usr/local/bundle/gems/bundler-2.3.22/exe/bundle:48:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.3.22/exe/bundle:36:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'
/usr/local/lib/ruby/3.1.0/socket.rb:456:in `__write_nonblock': Connection reset by peer (Errno::ECONNRESET)
        from /usr/local/lib/ruby/3.1.0/socket.rb:456:in `write_nonblock'
        from /usr/local/lib/ruby/3.1.0/net/protocol.rb:279:in `block in write0'
        from /usr/local/lib/ruby/3.1.0/net/protocol.rb:277:in `each'
        from /usr/local/lib/ruby/3.1.0/net/protocol.rb:277:in `each_with_index'
        from /usr/local/lib/ruby/3.1.0/net/protocol.rb:277:in `write0'
        from /usr/local/lib/ruby/3.1.0/net/protocol.rb:250:in `block in write'
        from /usr/local/lib/ruby/3.1.0/net/protocol.rb:267:in `writing'
        from /usr/local/lib/ruby/3.1.0/net/protocol.rb:249:in `write'
        from /usr/local/lib/ruby/3.1.0/net/http/generic_request.rb:189:in `send_request_with_body'
        from /usr/local/lib/ruby/3.1.0/net/http/generic_request.rb:123:in `exec'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1568:in `block in transport_request'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1566:in `catch'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1566:in `transport_request'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1539:in `request'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1532:in `block in request'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:966:in `start'
        from /usr/local/lib/ruby/3.1.0/net/http.rb:1530:in `request'
        from /usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/default_api.rb:82:in `_request'
        from /usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/default_api.rb:59:in `_post_text'
        from /usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/write_api.rb:214:in `write_raw'
        from /usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/write_api.rb:186:in `write'
        from /senec-importer/src/flux_writer.rb:17:in `push'
        from /senec-importer/src/flux_writer.rb:11:in `push'
        from /senec-importer/src/import.rb:36:in `process'
        from /senec-importer/src/import.rb:11:in `block in run'
        from /senec-importer/src/import.rb:10:in `each'
        from /senec-importer/src/import.rb:10:in `run'
        from src/main.rb:20:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:486:in `exec'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:25:in `start'
        from /usr/local/bundle/gems/bundler-2.3.22/exe/bundle:48:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.3.22/exe/bundle:36:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'
```

**Comment by ledermann** [comment]
Hier gibt es offenbar ein Verbindungsproblem zu InfluxDB. Bitte prüfen:
- Ist InfluxDB wirklich unter `192.168.200.222` erreichbar?
- Ist der Port `8086` offen?

Wie in https://github.com/solectrus/senec-importer/issues/2#issuecomment-1268398225 beschrieben, muss InfluxDB für den Import so eingerichtet sein, dass der Service von außen auch erreichbar ist. Das ist im Setup der Inhouse-Installation nämlich normalerweise nicht der Fall.

**Comment by Twooearly** [comment]
- Wie prüfe ich, ob die InfluxDB erreichbar ist? `192.168.200.222` ist die lokale IP des Servers auf dem alles läuft (Sowohl InfluxDB als auch das Interface, der Importer, etc.)
- Muss ich den Port im Router öffnen, obwohl es im lokalen Netzwerk ist? Ich habe in der `docker-compose.yml` den Port wie in #2  eingetragen

**Comment by ledermann** [comment]
Folgendes muss funktionieren:

```bash
$ curl -I http://192.168.200.222:8086
```

Das Ergebnis muss ein `200 OK` sein, also z.B. so aussehen:
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public, max-age=3600
Content-Length: 515
Content-Type: text/html; charset=utf-8
Etag: "51516182443"
Last-Modified: Fri, 16 Sep 2022 18:24:43 GMT
X-Influxdb-Build: OSS
X-Influxdb-Version: v2.5.1
Date: Fri, 04 Nov 2022 14:32:24 GMT
```

**Comment by Twooearly** [comment]
Vielen Dank! Das habe ich mittlerweile korrigiert, im docker-compose.yml file waren die Ports an falscher Stelle eingetragen.
Nun kommt aber eine andere Fehlermeldung:

```
root@homeserver:/var/lib/docker/history# docker run -it --rm            --env-file .env            --env INFLUX_HOST=192.168.200.222            -v /var/lib/docker/history/data:/data            ghcr.io/solectrus/senec-importer
SENEC CSV importer for SOLECTRUS
https://github.com/solectrus/senec-importer
Copyright (c) 2020,2022 Georg Ledermann, released under the MIT License

Using Ruby 3.1.2 on platform x86_64-linux-musl
Pushing to InfluxDB at http://192.168.200.222:8086, bucket my-solectrus-bucket

Importing data from /data ...
Importing /data/S21627181110462487540422709-week-10-2022.csv... bundler: failed to load command: src/main.rb (src/main.rb)
/usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/default_api.rb:106:in `_request': unauthorized access (InfluxDB2::InfluxError)
        from /usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/default_api.rb:59:in `_post_text'
        from /usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/write_api.rb:214:in `write_raw'
        from /usr/local/bundle/gems/influxdb-client-2.7.0/lib/influxdb2/client/write_api.rb:186:in `write'
        from /senec-importer/src/flux_writer.rb:17:in `push'
        from /senec-importer/src/flux_writer.rb:11:in `push'
        from /senec-importer/src/import.rb:36:in `process'
        from /senec-importer/src/import.rb:11:in `block in run'
        from /senec-importer/src/import.rb:10:in `each'
        from /senec-importer/src/import.rb:10:in `run'
        from src/main.rb:20:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:486:in `exec'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/cli.rb:25:in `start'
        from /usr/local/bundle/gems/bundler-2.3.22/exe/bundle:48:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.3.22/exe/bundle:36:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'
```

Ich vermute es hat was mit dem Token zu tun, aber da stimmen eigentlich alle Angaben...

**Comment by ledermann** [comment]
Ja, ein fehlendes oder falsches Token ist vermutlich die Ursache. Der Importer erwartet ein Token mit Schreibberechtigung (!) in der Umgebungsvariable `INFLUX_TOKEN`. Es muss dort das Token stehen, mit dem InfluxDB konfiguriert wurde. Die entsprechende Zeile in der Anleitung ist diese hier:
https://github.com/solectrus/hosting/blob/main/step-by-step/in-house/.env#L49

Notfalls lässt sich auch ein neues Token über das InfluxDB-Frontend erstellen.

**Comment by Twooearly** [comment]
Ja danke!! Jetzt hat es endlich geklappt. Vielen, vielen Dank für die schnelle Hilfe und viel Erfolg weiterhin mit der App! Ich finde die super :D
