### ISSUE TITLE
Error during inport of csv file

### ISSUE THREAD

**Issue by DanStasiak** [solectrus/senec-importer#39]
after I follow all instructions and run the command "docker run -it --rm --env-file .env  --mount type=bind,source="$PWD/csv",target=/data,readonly --network=solectrus_default  ghcr.io/solectrus/senec-importer"
the command ends with a error:

Importing data from /data ...
Importing /data/S27525591196576782540161857-week-1-2023.csv... bundler: failed to load command: src/main.rb (src/main.rb)
/usr/local/lib/ruby/3.2.0/time.rb:196:in `make_time': no time information in " CET" (ArgumentError)

        raise ArgumentError, "no time information in #{date.inspect}"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /usr/local/lib/ruby/3.2.0/time.rb:383:in `parse'
        from /senec-importer/src/solectrus_record.rb:109:in `parse_time'
        from /senec-importer/src/solectrus_record.rb:17:in `time'
        from /senec-importer/src/solectrus_record.rb:11:in `to_h'
        from /senec-importer/src/import.rb:39:in `block in process'
        from /usr/local/lib/ruby/3.2.0/csv/table.rb:938:in `each'
        from /usr/local/lib/ruby/3.2.0/csv/table.rb:938:in `each'
        from /senec-importer/src/import.rb:36:in `map'
        from /senec-importer/src/import.rb:36:in `process'
        from /senec-importer/src/import.rb:14:in `block in run'
        from /senec-importer/src/import.rb:13:in `each'
        from /senec-importer/src/import.rb:13:in `run'
        from src/main.rb:23:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
        from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
        from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'

Here is my csv file.

[S27525591196576782540161857-week-1-2023.csv](https://github.com/solectrus/senec-importer/files/11534858/S27525591196576782540161857-week-1-2023.csv)

**Comment by ledermann** [comment]
Thank you for this precise report. Looking at your CSV file, I see that the column headings are in **English**, while the importer expects **German** headings. This causes the import to fail.

Upon further investigation, I have found that the selected language of the user profile in `mein-senec.de` determines the column headings. Currently, the available languages are English, German, and Italian.

So, the quick fix for your problem is to change the language to German, then download all the CSV files again and restart the importer.

The long-term solution to this issue must be a change of the importer to handle all three languages. I will tackle this in the near future.
