### ISSUE TITLE
InfluxDB nicht erreichbar: Failed to open TCP connection

### ISSUE THREAD

**Issue by Twooearly** [solectrus/senec-importer#5]
Also lange ist es her, dass ich mich letztes Mal gemeldet habe und soweit hat auch alles sehr gut funktioniert, Dankeschön erstmal!
Ich habe mir mir großen Interesse die Version für den Raspberry Pi angeschaut und ausprobiert. Das hat bis jetzt auch perfekt funktioniert. Nur habe ich wie beim letzten Mal ein paar Probleme bei dem Import der alten Senec Dateien. Anscheinen probiert das Script sich mit einer IP zu verbinden, die nicht existiert.
Ich hänge einfach mal den Log an hier an:

```
twooearly@rapberrypi:~/solectrus/history-data $ sudo su
root@rapberrypi:/home/twooearly/solectrus/history-data# docker run -it --rm            --env-file .env            --env INFLUX_HOST=192.168.178.26            -v /home/twooearly/solectrus/history-data/Senec_Data:/data            ghcr.io/solectrus/senec-importer
SENEC CSV importer for SOLECTRUS
https://github.com/solectrus/senec-importer
Copyright (c) 2020,2023 Georg Ledermann, released under the MIT License

Using Ruby 3.2.1 on platform aarch64-linux-musl
Pushing to InfluxDB at http://192.168.178.26:8086, bucket my-solectrus-bucket

Importing data from /data ...
Importing /data/209927-week-1-2023.csv... bundler: failed to load command: src/main.rb (src/main.rb)
/usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:109:in `rescue in _request': Failed to open TCP connection to 192.168.178.26:8086 (execution expired) (InfluxDB2::InfluxError)
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:108:in `_request'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:59:in `_post_text'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:214:in `write_raw'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:186:in `write'
        from /senec-importer/src/flux_writer.rb:17:in `push'
        from /senec-importer/src/flux_writer.rb:11:in `push'
        from /senec-importer/src/import.rb:36:in `process'
        from /senec-importer/src/import.rb:11:in `block in run'
        from /senec-importer/src/import.rb:10:in `each'
        from /senec-importer/src/import.rb:10:in `run'
        from src/main.rb:20:in `<top (required)>'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:45:in `block in <top (required)>'
        from /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:33:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
/usr/local/lib/ruby/3.2.0/net/http.rb:1271:in `initialize': Failed to open TCP connection to 192.168.178.26:8086 (execution expired) (Net::OpenTimeout)
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1271:in `open'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1271:in `block in connect'
        from /usr/local/lib/ruby/3.2.0/timeout.rb:189:in `block in timeout'
        from /usr/local/lib/ruby/3.2.0/timeout.rb:196:in `timeout'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1269:in `connect'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1248:in `do_start'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1237:in `start'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1817:in `request'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:82:in `_request'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:59:in `_post_text'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:214:in `write_raw'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:186:in `write'
        from /senec-importer/src/flux_writer.rb:17:in `push'
        from /senec-importer/src/flux_writer.rb:11:in `push'
        from /senec-importer/src/import.rb:36:in `process'
        from /senec-importer/src/import.rb:11:in `block in run'
        from /senec-importer/src/import.rb:10:in `each'
        from /senec-importer/src/import.rb:10:in `run'
        from src/main.rb:20:in `<top (required)>'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:45:in `block in <top (required)>'
        from /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:33:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
```

- Die Dateien sind alle in dem angegebenen Pfad `/home/twooearly/solectrus/history-data/Senec_Data` 
- Inhalt der `.env` Datei:
```
# Credentials of your InfluxDB installation
INFLUX_HOST=192.168.200.200
INFLUX_SCHEMA=http
INFLUX_PORT=8086
INFLUX_TOKEN=*stimmt mit dem Token aus der .env im docker Verzeichnis überein*
INFLUX_ORG=solectrus
INFLUX_BUCKET=my-solectrus-bucket
```

Ich hoffe, dass sie damit arbeiten können. Danke im Voraus für die Hilfe und einen schönen Tag 😃

**Comment by ledermann** [comment]
Ja, die Nutzung des Datenimports ist etwas hakelig und ich hatte es unnötig kompliziert gemacht. Die Anleitung im [README](https://github.com/solectrus/senec-importer/blob/main/README.md) habe ich gerade überarbeitet.

Hier in Ihrem Fall konnte keine Verbindung zu InfluxDB aufgebaut werden, da dieser Dienst nicht nach außen durchgereicht wird. Es muss stattdessen das **interne** Netzwerk, das von Docker-Compose aufgespannt wurde, verwendet werden. Dann ist InfluxDB auch über den normalen Hostnamen `influxdb` erreichbar.

Der korrekte Befehlt lautet in Ihrem Fall:

```bash
docker run -it --rm \
           --env-file .env \
           --volume=/home/twooearly/solectrus/history-data/Senec_Data:/data \
           --network=solectrus_default \
           ghcr.io/solectrus/senec-importer
```

(Falls das Netzwerk nicht `solectrus_default` heißen sollte, bitte vorher mit `docker network ls` prüfen und ggfs. anpassen)

WICHTIG: Es ist die exakt gleiche .env-Datei zu verwenden, die auch SOLECTRUS verwendet, also mit diesen Einträgen:

```
INFLUX_HOST=influxdb
INFLUX_SCHEMA=http
INFLUX_PORT=8086
INFLUX_TOKEN=my-super-secret-admin-token
```

**Comment by Twooearly** [comment]
Mit der neuen Anleitung wurde dieser Fehler gelöst, nur hat sich beim testen ein neuer Fehler aufgetan. Ich habe das Verzeichnis nochmal neu geändert, sodass man den Prozess mit derselben `.env` Datei ausführen kann. Die einzige Änderung, die dafür nötig war, ist, dass man den Wert `INFLUX_TOKEN="Hier den Token einfügen"` in die `.env` Datei anhängt, weil dieser davor nicht vorhanden war.
Wenn ich den Prozess starte, importiert er auch die ersten 2 Dateien, bei der dritten, kommt jedoch diese Fehlermeldung:

```
twooearly@rapberrypi:~/solectrus $ docker run -it --rm \
>            --env-file .env \
>            --volume=./csv:/data \
>            --network=solectrus_default \
>            ghcr.io/solectrus/senec-importer
SENEC CSV importer for SOLECTRUS
https://github.com/solectrus/senec-importer
Copyright (c) 2020,2023 Georg Ledermann, released under the MIT License

Using Ruby 3.2.1 on platform aarch64-linux-musl
Pushing to InfluxDB at http://influxdb:8086, bucket my-solectrus-bucket

Importing data from /data ...
Importing /data/209927-week-1-2023.csv... 1995 points imported
Importing /data/209927-week-10-2022.csv... 2003 points imported
Importing /data/209927-week-11-2022.csv... bundler: failed to load command: src/main.rb (src/main.rb)
/usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:109:in `rescue in _request': Net::ReadTimeout with #<TCPSocket:(closed)> (InfluxDB2::InfluxError)
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:108:in `_request'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:59:in `_post_text'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:214:in `write_raw'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:186:in `write'
        from /senec-importer/src/flux_writer.rb:17:in `push'
        from /senec-importer/src/flux_writer.rb:11:in `push'
        from /senec-importer/src/import.rb:36:in `process'
        from /senec-importer/src/import.rb:11:in `block in run'
        from /senec-importer/src/import.rb:10:in `each'
        from /senec-importer/src/import.rb:10:in `run'
        from src/main.rb:20:in `<top (required)>'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:45:in `block in <top (required)>'
        from /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:33:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
/usr/local/lib/ruby/3.2.0/net/protocol.rb:229:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
        from /usr/local/lib/ruby/3.2.0/net/protocol.rb:199:in `readuntil'
        from /usr/local/lib/ruby/3.2.0/net/protocol.rb:209:in `readline'
        from /usr/local/lib/ruby/3.2.0/net/http/response.rb:158:in `read_status_line'
        from /usr/local/lib/ruby/3.2.0/net/http/response.rb:147:in `read_new'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1862:in `block in transport_request'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1853:in `catch'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1853:in `transport_request'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1826:in `request'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1819:in `block in request'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1238:in `start'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1817:in `request'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:82:in `_request'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:59:in `_post_text'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:214:in `write_raw'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:186:in `write'
        from /senec-importer/src/flux_writer.rb:17:in `push'
        from /senec-importer/src/flux_writer.rb:11:in `push'
        from /senec-importer/src/import.rb:36:in `process'
        from /senec-importer/src/import.rb:11:in `block in run'
        from /senec-importer/src/import.rb:10:in `each'
        from /senec-importer/src/import.rb:10:in `run'
        from src/main.rb:20:in `<top (required)>'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:45:in `block in <top (required)>'
        from /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:33:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'

```

**Comment by ledermann** [comment]
Ok, das mit dem Token habe ich korrigiert: Es wird nun `INFLUX_TOKEN_WRITE` genommen, falls vorhanden, ansonsten `INFLUX_TOKEN`. Somit ist es jetzt wirklich identisch mit anderen .env-Datei.

Die Fehlermeldung zeigt einen Timeout an. Vielleicht ist der Raspi zu langsam? Ich habe hier einen _Raspberry Pi 4 Model B Rev 1.4_, bei dem es problemlos geklappt hat.

Sicherheitshalber habe ich das Timeout-Limit erhöht (vorher 10 Sekunden, jetzt 30 Sekunden). Per ENV kann das bei Bedarf noch weiter erhöht werden, die Variablen heißen:

```
INFLUX_OPEN_TIMEOUT
INFLUX_READ_TIMEOUT
INFLUX_WRITE_TIMEOUT
```

Bitte jetzt neues Docker Image holen (`docker pull ghcr.io/solectrus/senec-importer`, es gibt noch keine Versionierung) und noch mal versuchen.

**Comment by Twooearly** [comment]
Vielen Dank, das wurde auch behoben, jetzt werden die ersten 5 Tabellen importiert und danach kommt der Timeout Fehler von der Influxdb
(
```
twooearly@rapberrypi:~/solectrus $ docker run -it --rm            --env-file .env            --volume=./csv:/data            --network=solectrus_default            ghcr.io/solectrus/senec-importer
SENEC CSV importer for SOLECTRUS
https://github.com/solectrus/senec-importer
Copyright (c) 2020,2023 Georg Ledermann, released under the MIT License

Using Ruby 3.2.1 on platform aarch64-linux-musl
Pushing to InfluxDB at http://influxdb:8086, bucket my-solectrus-bucket

Importing data from /data ...
Importing /data/209927-week-1-2023.csv... 1995 points imported
Importing /data/209927-week-10-2022.csv... 2003 points imported
Importing /data/209927-week-11-2022.csv... 2006 points imported
Importing /data/209927-week-12-2022.csv... 1208 points imported
Importing /data/209927-week-13-2022.csv... 443 points imported
Importing /data/209927-week-14-2022.csv... bundler: failed to load command: src/main.rb (src/main.rb)
/usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:106:in `_request': unexpected error writing points to database: timeout (InfluxDB2::InfluxError)
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:59:in `_post_text'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:214:in `write_raw'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:186:in `write'
        from /senec-importer/src/flux_writer.rb:17:in `push'
        from /senec-importer/src/flux_writer.rb:11:in `push'
        from /senec-importer/src/import.rb:41:in `process'
        from /senec-importer/src/import.rb:13:in `block in run'
        from /senec-importer/src/import.rb:12:in `each'
        from /senec-importer/src/import.rb:12:in `run'
        from src/main.rb:20:in `<top (required)>'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
        from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:45:in `block in <top (required)>'
        from /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:33:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'

```
)
Ich kann mir dehr gut vorstellen, dass der Raspi zu langsam ist, aber mir nicht unbedingt erklären warum... Ich habe auch einen _Raspberry Pi 4 Model B_ mit _4GB RAM_ . Es läuft frisch installiertes Raspberry Pi OS Lite 64 Bit und es läuft nichts anderes außer diese Applikation als Docker-Container. Hilft es etwas den Timeout weiter zu erhören, oder gibt es noch einen anderen Ansatz?

**Comment by ledermann** [comment]
Das ist sehr eigenartig. Ich werde hierzu weitere eigene Experimente anstellen und versuchen, das irgendwie zu reproduzieren. 

Bis dahin könnte es lohnenswert sein, den Timeout zu erhöhen (auch deutlich) und/oder es mehrfach zu versuchen.

**Comment by Twooearly** [comment]
Okay, vielen Dank

**Comment by ledermann** [comment]
Mal zum Vergleich, mein Raspi hat 8GB RAM, 32GB SSD. Genauer:

```
$ uname -a
Linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux

$ cat /sys/firmware/devicetree/base/model
Raspberry Pi 4 Model B Rev 1.4

$ free -h
               total        used        free      shared  buff/cache   available
Mem:           7.6Gi       830Mi       5.1Gi        15Mi       1.7Gi       6.7Gi
Swap:           99Mi          0B        99Mi

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        29G  3.6G   25G  13% /
devtmpfs        3.7G     0  3.7G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           1.6G  1.9M  1.6G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
/dev/mmcblk0p1  255M   31M  225M  12% /boot
tmpfs           782M     0  782M   0% /run/user/1000
```

Es laufen verschiedene Docker-Container, d.h. insbesondere SOLECTRUS. Der Import eines Jahres (also 52 CSV-Dateien) dauert ca. eine Minute und läuft fehlerfrei durch. Das sieht so aus:

```
$ time \
    docker run -it --rm \
    --env-file .env \
    --network=solectrus_default \
    --volume=./csv/2022:/data \
    ghcr.io/solectrus/senec-importer

SENEC CSV importer for SOLECTRUS
https://github.com/solectrus/senec-importer
Copyright (c) 2020,2023 Georg Ledermann, released under the MIT License

Using Ruby 3.2.1 on platform aarch64-linux-musl
Pushing to InfluxDB at http://influxdb:8086, bucket SENEC

Importing data from /data ...
Importing /data/week-1-2022.csv... 2000 points imported
Importing /data/week-10-2022.csv... 1989 points imported
Importing /data/week-11-2022.csv... 1994 points imported
Importing /data/week-12-2022.csv... 1249 points imported
Importing /data/week-13-2022.csv... 838 points imported
Importing /data/week-14-2022.csv... 1392 points imported
Importing /data/week-15-2022.csv... 2003 points imported
Importing /data/week-16-2022.csv... 1999 points imported
Importing /data/week-17-2022.csv... 2007 points imported
Importing /data/week-18-2022.csv... 2009 points imported
Importing /data/week-19-2022.csv... 2005 points imported
Importing /data/week-2-2022.csv... 1999 points imported
Importing /data/week-20-2022.csv... 2005 points imported
Importing /data/week-21-2022.csv... 2003 points imported
Importing /data/week-22-2022.csv... 2004 points imported
Importing /data/week-23-2022.csv... 2004 points imported
Importing /data/week-24-2022.csv... 2003 points imported
Importing /data/week-25-2022.csv... 2006 points imported
Importing /data/week-26-2022.csv... 2005 points imported
Importing /data/week-27-2022.csv... 2006 points imported
Importing /data/week-28-2022.csv... 2003 points imported
Importing /data/week-29-2022.csv... 1944 points imported
Importing /data/week-3-2022.csv... 2003 points imported
Importing /data/week-30-2022.csv... 2004 points imported
Importing /data/week-31-2022.csv... 2008 points imported
Importing /data/week-32-2022.csv... 2004 points imported
Importing /data/week-33-2022.csv... 2004 points imported
Importing /data/week-34-2022.csv... 2003 points imported
Importing /data/week-35-2022.csv... 2002 points imported
Importing /data/week-36-2022.csv... 2002 points imported
Importing /data/week-37-2022.csv... 1963 points imported
Importing /data/week-38-2022.csv... 2002 points imported
Importing /data/week-39-2022.csv... 2004 points imported
Importing /data/week-4-2022.csv... 2000 points imported
Importing /data/week-40-2022.csv... 2004 points imported
Importing /data/week-41-2022.csv... 2004 points imported
Importing /data/week-42-2022.csv... 2005 points imported
Importing /data/week-43-2022.csv... 2017 points imported
Importing /data/week-44-2022.csv... 2004 points imported
Importing /data/week-45-2022.csv... 2000 points imported
Importing /data/week-46-2022.csv... 2003 points imported
Importing /data/week-47-2022.csv... 2001 points imported
Importing /data/week-48-2022.csv... 2005 points imported
Importing /data/week-49-2022.csv... 2003 points imported
Importing /data/week-5-2022.csv... 2004 points imported
Importing /data/week-50-2022.csv... 2004 points imported
Importing /data/week-51-2022.csv... 2007 points imported
Importing /data/week-52-2022.csv... 2003 points imported
Importing /data/week-6-2022.csv... 2006 points imported
Importing /data/week-7-2022.csv... 2005 points imported
Importing /data/week-8-2022.csv... 2006 points imported
Importing /data/week-9-2022.csv... 2000 points imported
Imported 52 files


real	1m6.586s
user	0m0.138s
sys	0m0.085s

$ uptime
19:04:39 up 5 days, 13:19,  1 user,  load average: 1.00, 0.63, 0.45
```

Es funktioniert bei mir alles tadellos. Momentan habe ich keine Idee, woran das Timeout-Problem bei Ihnen liegen könnte.

**Comment by Twooearly** [comment]
Hm der einzige Unterschied ist, dass bei
```
$ cat /sys/firmware/devicetree/base/model
Raspberry Pi 4 Model B Rev 1.2
```
ausgegeben wird. Also wahrscheinlich, weil bei mir das 4 GB Modell zum Einsatz kommt.
Ich benutze im Moment eine 16GB Micro SD Karte, die aber auch noch zu 80% frei ist. Ich probiere auch nochmal ein paar Sachen, trotzdem schonmal Danke für ihre Bemühungen.

**Comment by Twooearly** [comment]
Also, ich habe mich seit langem mal wieder mit dem Projekt beschäftigt, da ich letztens eine neue Micro SD Karte für den Raspi gesehen habe und mit gekauft habe. Ich hatte lange gesucht, warum der Raspi langsam sein könnte und es lag letztendlich auch am Speicher. Die SD-Karte war schon recht lange benutzt und somit auch sehr langsam. Nicht einmal Windows kann die richtig lesen. Ich habe alles neu aufgesetzt und auch den Importer über die alten Dateien laufen lassen und es hat alles perfekt funktioniert.
Vielen, vielen Dank für die vielen Bemühungen und ganz viel Erfolg weiterhin mit diesem und anderen Projekten.

LG Felix
